# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20170722_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(related_name='Courses', to='student.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='professor',
            field=models.ManyToManyField(related_name='Subject', to='student.Professor'),
        ),
    ]
