# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20170722_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='professor',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
